language: php
php:
  - 7.3
services:
  - docker
before_script:
  - composer install
script:
  - ./vendor/bin/phpcs --standard=ModernPHP src
  - composer test
  - docker build . -t remy-theroux/requests-stubs:$TRAVIS_BRANCH
  - docker push remy-theroux/requests-stubs:$TRAVIS_BRANCH
