name: CI

on: [push]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          coverage: none
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Install dependencies
        run: composer install
      - name: Code style
        run: vendor/bin/phpcs --standard=ModernPhp src
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          coverage: none
      - name: git Actions
        uses: srt32/git-actions@v0.0.3
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Execute tests
        run: composer test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building docker image
        run: docker build . -t remy-theroux/mocks-server:${GITHUB_REF##*/}
      - name: Pushing docker image
        run: docker push remy-theroux/mocks-server:${GITHUB_REF##*/}
