name: CI

on: [push]

jobs:
  quality:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          coverage: none
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Install dependencies
        run: composer install
      - name: Code style
        run: vendor/bin/phpcs --standard=ModernPhp src
  tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          coverage: none
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Execute tests
        run: scripts/start-server.sh && vendor/bin/behat -v && scripts/stop-server.sh
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Building docker image
        run: docker build . -t remy-theroux/mocks-server:${{ github.ref }}
      - name: Pushing docker image
        run: docker push remy-theroux/mocks-server:${{ github.ref }}
